export interface MandiItem {
  id: string;
  cropNameTe: string;
  cropNameEn: string;
  variety: string;
  imageUrl: string;
  currentPrice: number;
  unit: string;
  priceChange: number;
  trend: 'up' | 'down' | 'stable';
  trendTextTe: string;
  marketNameTe: string;
  marketNameEn: string;
  distanceKm: number;
  minPrice: number;
  maxPrice: number;
  date: string;
}

export const MANDI_PRICES: MandiItem[] = [
  {
    id: 'mandi-chilli',
    cropNameTe: 'తేజ ఎండు మిర్చి',
    cropNameEn: 'Teja Dry Chilli',
    variety: 'తేజ ప్రీమియం (A-Grade)',
    imageUrl: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=800&q=85',
    currentPrice: 19400,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: 350,
    trend: 'up',
    trendTextTe: 'ధర పెరుగుతోంది (+₹350)',
    marketNameTe: 'ఖమ్మం మార్కెట్ యార్డ్',
    marketNameEn: 'Khammam Agricultural Market',
    distanceKm: 18,
    minPrice: 17200,
    maxPrice: 20800,
    date: 'ఈ రోజు (Live)',
  },
  {
    id: 'mandi-tomato',
    cropNameTe: 'టమాట',
    cropNameEn: 'Tomato (Local & Hybrid)',
    variety: 'హైబ్రిడ్ రకం',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=85',
    currentPrice: 3200,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: 400,
    trend: 'up',
    trendTextTe: 'ధర పెరుగుతోంది (+₹400)',
    marketNameTe: 'సూర్యాపేట మార్కెట్',
    marketNameEn: 'Suryapet Vegetable Market',
    distanceKm: 12,
    minPrice: 2600,
    maxPrice: 3600,
    date: 'ఈ రోజు (Live)',
  },
  {
    id: 'mandi-paddy',
    cropNameTe: 'వరి (సాంబ మసూరి BPT)',
    cropNameEn: 'Paddy (Fine Variety)',
    variety: 'BPT-5204 Grade-A',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=85',
    currentPrice: 2480,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: 60,
    trend: 'up',
    trendTextTe: 'పెరుగుతోంది (+₹60)',
    marketNameTe: 'వరంగల్ మార్కెట్',
    marketNameEn: 'Warangal Enumamula Market',
    distanceKm: 24,
    minPrice: 2320,
    maxPrice: 2560,
    date: 'ఈ రోజు (Live)',
  },
  {
    id: 'mandi-cotton',
    cropNameTe: 'పత్తి',
    cropNameEn: 'Raw Cotton',
    variety: 'మధ్యస్థ పింజ',
    imageUrl: 'https://images.unsplash.com/photo-1606041008023-472dfb5e530f?auto=format&fit=crop&w=800&q=85',
    currentPrice: 7350,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: -80,
    trend: 'down',
    trendTextTe: 'తగ్గింది (-₹80)',
    marketNameTe: 'గుంటూరు మార్కెట్',
    marketNameEn: 'Guntur Market Yard',
    distanceKm: 42,
    minPrice: 6900,
    maxPrice: 7600,
    date: 'ఈ రోజు (Live)',
  },
  {
    id: 'mandi-onion',
    cropNameTe: 'ఉల్లిపాయ',
    cropNameEn: 'Red Onion',
    variety: 'స్థానిక రకం',
    imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=800&q=85',
    currentPrice: 2800,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: 0,
    trend: 'stable',
    trendTextTe: 'ధర స్థిరంగా ఉంది',
    marketNameTe: 'నిజామాబాద్ మార్కెట్',
    marketNameEn: 'Nizamabad Mandi',
    distanceKm: 31,
    minPrice: 2200,
    maxPrice: 3200,
    date: 'ఈ రోజు (Live)',
  },
  {
    id: 'mandi-turmeric',
    cropNameTe: 'పసుపు',
    cropNameEn: 'Turmeric (Finger)',
    variety: 'ఫింగర్ వెరైటీ',
    imageUrl: 'https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?auto=format&fit=crop&w=800&q=85',
    currentPrice: 13500,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: 450,
    trend: 'up',
    trendTextTe: 'పెరుగుతోంది (+₹450)',
    marketNameTe: 'నిజామాబాద్ మార్కెట్',
    marketNameEn: 'Nizamabad Mandi',
    distanceKm: 31,
    minPrice: 12500,
    maxPrice: 15000,
    date: 'ఈ రోజు (Live)',
  },
  {
    id: 'mandi-groundnut',
    cropNameTe: 'వేరుశనగ',
    cropNameEn: 'Groundnut (Pods)',
    variety: 'కదిరి-6',
    imageUrl: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=800&q=85',
    currentPrice: 6200,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: -120,
    trend: 'down',
    trendTextTe: 'తగ్గింది (-₹120)',
    marketNameTe: 'అనంతపురం మార్కెట్',
    marketNameEn: 'Anantapur Market',
    distanceKm: 150,
    minPrice: 5800,
    maxPrice: 6800,
    date: 'ఈ రోజు (Live)',
  },
  {
    id: 'mandi-maize',
    cropNameTe: 'మొక్కజొన్న',
    cropNameEn: 'Maize (Corn)',
    variety: 'హైబ్రిడ్',
    imageUrl: 'https://images.unsplash.com/photo-1601397441551-8664ebc40e15?auto=format&fit=crop&w=800&q=85',
    currentPrice: 2250,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: 20,
    trend: 'up',
    trendTextTe: 'పెరుగుతోంది (+₹20)',
    marketNameTe: 'కరీంనగర్ మార్కెట్',
    marketNameEn: 'Karimnagar Market Yard',
    distanceKm: 60,
    minPrice: 2090,
    maxPrice: 2350,
    date: 'ఈ రోజు (Live)',
  },
  {
    id: 'mandi-redgram',
    cropNameTe: 'కందులు',
    cropNameEn: 'Red Gram (Toor Dal)',
    variety: 'ఆశ వెరైటీ',
    imageUrl: 'https://images.unsplash.com/photo-1582283995893-9c849cf24eb2?auto=format&fit=crop&w=800&q=85',
    currentPrice: 10500,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: -50,
    trend: 'stable',
    trendTextTe: 'దాదాపు స్థిరంగా ఉంది',
    marketNameTe: 'సూర్యాపేట మార్కెట్',
    marketNameEn: 'Suryapet Market Yard',
    distanceKm: 12,
    minPrice: 9500,
    maxPrice: 11200,
    date: 'ఈ రోజు (Live)',
  },
  {
    id: 'mandi-greengram',
    cropNameTe: 'పెసలు',
    cropNameEn: 'Green Gram (Moong)',
    variety: 'సాధారణ రకం',
    imageUrl: 'https://images.unsplash.com/photo-1600626333421-25a25e2e42d7?auto=format&fit=crop&w=800&q=85',
    currentPrice: 8500,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: 150,
    trend: 'up',
    trendTextTe: 'పెరుగుతోంది (+₹150)',
    marketNameTe: 'మహబూబాబాద్ మార్కెట్',
    marketNameEn: 'Mahabubabad Market',
    distanceKm: 45,
    minPrice: 7800,
    maxPrice: 9100,
    date: 'ఈ రోజు (Live)',
  },
  {
    id: 'mandi-mango',
    cropNameTe: 'మామిడి',
    cropNameEn: 'Mango (Banganapalli)',
    variety: 'బంగినపల్లి',
    imageUrl: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=800&q=85',
    currentPrice: 4500,
    unit: 'క్వింటాల్ (Qtl)',
    priceChange: 300,
    trend: 'up',
    trendTextTe: 'పెరుగుతోంది (+₹300)',
    marketNameTe: 'నుజ్జువీడు మార్కెట్',
    marketNameEn: 'Nuzvid Fruit Market',
    distanceKm: 110,
    minPrice: 3500,
    maxPrice: 5500,
    date: 'ఈ రోజు (Live)',
  }
];
